### ISSUE TITLE
Can't put Source

### ISSUE THREAD

**Issue by dave21458** [dave21458/Phomium#2]
I tried to upload Source code...it Failed after about 2 hours...
Then tried to zip it and upload that failed

**Comment by joshuaebowling** [comment]
I'm not sure what the max size of a single commit is, but from everything I'm reading the binary assets should go into a separate repository that way their diffs don't get added to history which could easily balloon beyond the already large binary file size.  Let's talk later today about strategy, if you have time.

**Comment by dave21458** [comment]
Having issues with syncing...it won't keeps erroring out.
Think I should move to a new repository?

**Comment by dave21458** [comment]
FYI Git does not like repos over 1 gig....also files over 100mb...

**Comment by dave21458** [comment]
Finally .... I got git back to working right again I hope.....
Had to delete local copy then clone repo ..
Adding Full Source project to repo is not a good thing 
... do you need the source code?

**Comment by joshuaebowling** [comment]
no, I'm just going to be working on adding node and restify in a branch and setup some demos with it and help connect it to your api call from within your app.
